import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import products from "../products.json";

const Home: NextPage = () => {
  console.log("products", products);
  return (
    <div className={styles.container}>
      <Head>
        <title>The Shoe Sanctuary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          The <a href="https://nextjs.org">Shoe</a> Sanctuary
        </h1>

        <p className={styles.description}>Kicks from Beyond.</p>

        <ul className={styles.grid}>
          {products.map(({ title, description, price, image, id }, i) => (
            <li className={styles.card} key={id}>
              <a href="https://nextjs.org/docs">
                <Image src={image} alt="" height={350} width={500} />
                <div className={styles.info}>
                  <h2>{title}</h2>
                  <h3>£{price}</h3>
                </div>
                <p>{description}</p>
              </a>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
